/**
 * Mock printer data for TacticalMap demo
 */

import type { PrinterUnit } from './types'

export const MOCK_PRINTERS: PrinterUnit[] = [
  // Lab Alpha - Production line
  {
    id: 'printer-001',
    name: 'DM-ALPHA-01',
    model: 'Studio System',
    status: 'working',
    position: { x: 15, y: 25 },
    labId: 'lab-alpha',
    labName: 'Lab Alpha',
    jobProgress: 67,
    jobName: 'Bracket Assembly v2.3',
    health: {
      temperature: 72,
      humidity: 45,
      uptime: 1247,
      errorCount: 0,
    },
    capabilities: {
      canPrint: true,
      canCalibrate: true,
      canQueue: true,
    },
    lastPing: new Date(),
  },
  {
    id: 'printer-002',
    name: 'DM-ALPHA-02',
    model: 'Studio System',
    status: 'idle',
    position: { x: 25, y: 30 },
    labId: 'lab-alpha',
    labName: 'Lab Alpha',
    jobProgress: null,
    jobName: null,
    health: {
      temperature: 28,
      humidity: 42,
      uptime: 2891,
      errorCount: 1,
    },
    capabilities: {
      canPrint: true,
      canCalibrate: true,
      canQueue: true,
    },
    lastPing: new Date(),
  },
  {
    id: 'printer-003',
    name: 'DM-ALPHA-03',
    model: 'Shop System',
    status: 'working',
    position: { x: 20, y: 40 },
    labId: 'lab-alpha',
    labName: 'Lab Alpha',
    jobProgress: 23,
    jobName: 'Custom Tooling Set',
    health: {
      temperature: 85,
      humidity: 38,
      uptime: 567,
      errorCount: 0,
    },
    capabilities: {
      canPrint: true,
      canCalibrate: true,
      canQueue: true,
    },
    lastPing: new Date(),
  },

  // Lab Beta - R&D
  {
    id: 'printer-004',
    name: 'DM-BETA-01',
    model: 'InnoventX',
    status: 'calibrating',
    position: { x: 55, y: 20 },
    labId: 'lab-beta',
    labName: 'Lab Beta (R&D)',
    jobProgress: null,
    jobName: null,
    health: {
      temperature: 45,
      humidity: 50,
      uptime: 89,
      errorCount: 0,
    },
    capabilities: {
      canPrint: false,
      canCalibrate: true,
      canQueue: false,
    },
    lastPing: new Date(),
  },
  {
    id: 'printer-005',
    name: 'DM-BETA-02',
    model: 'Studio System',
    status: 'error',
    position: { x: 65, y: 25 },
    labId: 'lab-beta',
    labName: 'Lab Beta (R&D)',
    jobProgress: 45,
    jobName: 'Prototype Housing',
    health: {
      temperature: 92,
      humidity: 65,
      uptime: 234,
      errorCount: 3,
    },
    capabilities: {
      canPrint: false,
      canCalibrate: false,
      canQueue: false,
    },
    lastPing: new Date(Date.now() - 5000),
  },
  {
    id: 'printer-006',
    name: 'DM-BETA-03',
    model: 'InnoventX',
    status: 'idle',
    position: { x: 60, y: 35 },
    labId: 'lab-beta',
    labName: 'Lab Beta (R&D)',
    jobProgress: null,
    jobName: null,
    health: {
      temperature: 25,
      humidity: 48,
      uptime: 1456,
      errorCount: 0,
    },
    capabilities: {
      canPrint: true,
      canCalibrate: true,
      canQueue: true,
    },
    lastPing: new Date(),
  },

  // Lab Gamma - High volume
  {
    id: 'printer-007',
    name: 'DM-GAMMA-01',
    model: 'Production System',
    status: 'working',
    position: { x: 35, y: 65 },
    labId: 'lab-gamma',
    labName: 'Lab Gamma (Production)',
    jobProgress: 89,
    jobName: 'Batch Order #4521',
    health: {
      temperature: 78,
      humidity: 40,
      uptime: 4567,
      errorCount: 0,
    },
    capabilities: {
      canPrint: true,
      canCalibrate: true,
      canQueue: true,
    },
    lastPing: new Date(),
  },
  {
    id: 'printer-008',
    name: 'DM-GAMMA-02',
    model: 'Production System',
    status: 'working',
    position: { x: 45, y: 70 },
    labId: 'lab-gamma',
    labName: 'Lab Gamma (Production)',
    jobProgress: 12,
    jobName: 'Batch Order #4522',
    health: {
      temperature: 76,
      humidity: 42,
      uptime: 3890,
      errorCount: 0,
    },
    capabilities: {
      canPrint: true,
      canCalibrate: true,
      canQueue: true,
    },
    lastPing: new Date(),
  },
  {
    id: 'printer-009',
    name: 'DM-GAMMA-03',
    model: 'Shop System',
    status: 'offline',
    position: { x: 55, y: 68 },
    labId: 'lab-gamma',
    labName: 'Lab Gamma (Production)',
    jobProgress: null,
    jobName: null,
    health: {
      temperature: 0,
      humidity: 0,
      uptime: 0,
      errorCount: 0,
    },
    capabilities: {
      canPrint: false,
      canCalibrate: false,
      canQueue: false,
    },
    lastPing: new Date(Date.now() - 3600000),
  },

  // Lab Delta - Testing
  {
    id: 'printer-010',
    name: 'DM-DELTA-01',
    model: 'Studio System',
    status: 'idle',
    position: { x: 80, y: 50 },
    labId: 'lab-delta',
    labName: 'Lab Delta (Testing)',
    jobProgress: null,
    jobName: null,
    health: {
      temperature: 26,
      humidity: 44,
      uptime: 789,
      errorCount: 0,
    },
    capabilities: {
      canPrint: true,
      canCalibrate: true,
      canQueue: true,
    },
    lastPing: new Date(),
  },
  {
    id: 'printer-011',
    name: 'DM-DELTA-02',
    model: 'InnoventX',
    status: 'working',
    position: { x: 85, y: 60 },
    labId: 'lab-delta',
    labName: 'Lab Delta (Testing)',
    jobProgress: 55,
    jobName: 'Material Test Series',
    health: {
      temperature: 68,
      humidity: 46,
      uptime: 234,
      errorCount: 0,
    },
    capabilities: {
      canPrint: true,
      canCalibrate: true,
      canQueue: true,
    },
    lastPing: new Date(),
  },
]
