/**
 * Unified Correlation Types
 *
 * Single source of truth for experiment → activity mapping.
 * Shared across Nova orchestrator and main backend services.
 */

// ============================================================================
// Activity Status
// ============================================================================

/**
 * Normalized activity status values (lowercase to match INTERSECT gateway)
 */
export type ActivityStatus =
  | 'pending'
  | 'running'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'started';

/**
 * Legacy status format for event compatibility with older INTERSECT versions
 */
export type LegacyActivityStatus =
  | 'ACTIVITY_PENDING'
  | 'ACTIVITY_IN_PROGRESS'
  | 'ACTIVITY_COMPLETED'
  | 'ACTIVITY_FAILED'
  | 'ACTIVITY_CANCELED';

// ============================================================================
// Correlation Types
// ============================================================================

/**
 * Base correlation for tracking experiment → activity relationships.
 * Used by the gateway service for request correlation.
 */
export interface Correlation {
  /** The experiment run this activity belongs to */
  experimentRunId: string;
  /** Optional campaign ID for multi-experiment campaigns */
  campaignId?: string;
  /** Optional distributed tracing ID */
  traceId?: string;
}

/**
 * Extended correlation stored locally for workflow tracking.
 * Contains all information needed to trace an activity back to its experiment.
 */
export interface ActivityCorrelation {
  /** Unique identifier for correlation record (optional, DB may generate) */
  id?: string;
  /** INTERSECT activity ID */
  activityId: string;
  /** The experiment run this activity belongs to */
  experimentRunId: string;
  /** Optional campaign ID */
  campaignId?: string;
  /** Controller that executed this activity */
  controllerId: string;
  /** Name of the activity */
  activityName?: string;
  /** Workflow step ID this activity corresponds to */
  stepId?: string;
  /** Distributed tracing ID */
  traceId?: string;
  /** Current status of the activity */
  status?: ActivityStatus;
  /** When the correlation was created */
  createdAt: Date;
  /** Last update timestamp */
  updatedAt: Date;
  /** Phase this activity belongs to (design, execute, analyze) */
  phase?: string;
  /** Run number within DOE (if executing phase) */
  runNumber?: number;
  /** Step index within a run */
  stepIndex?: number;
  /** Total steps expected in this phase/run */
  totalSteps?: number;
  /** Progress percentage (0-100) */
  progress?: number;
  /** Data products generated by this activity */
  dataProducts?: string[];
  /** Error message if failed */
  error?: string;
}

// ============================================================================
// Data Product Mapping
// ============================================================================

/**
 * Maps INTERSECT data products to ADAM artifacts
 */
export interface DataProductMapping {
  /** Unique identifier */
  id?: string;
  /** INTERSECT product UUID */
  productUuid: string;
  /** Activity that produced this data */
  activityId: string;
  /** ADAM artifact ID (if synced) */
  artifactId?: string;
  /** Storage location URI */
  storageUri?: string;
  /** Content type (MIME) */
  contentType?: string;
  /** Additional metadata */
  metadata?: Record<string, string>;
  /** When the mapping was created */
  createdAt: Date;
}

// ============================================================================
// Correlation Store Interface
// ============================================================================

/**
 * Interface for storing and retrieving activity correlations.
 * Implementations may use in-memory storage, Redis, or database.
 */
export interface ICorrelationStore {
  /** Save a new correlation */
  save(correlation: ActivityCorrelation): Promise<void>;
  /** Find correlation by activity ID */
  findByActivityId(activityId: string): Promise<ActivityCorrelation | null>;
  /** Find all correlations for an experiment run */
  findByExperimentRunId(experimentRunId: string): Promise<ActivityCorrelation[]>;
  /** Find correlation by step ID */
  findByStepId(stepId: string): Promise<ActivityCorrelation | null>;
  /** Update activity status */
  updateStatus(activityId: string, status: ActivityStatus): Promise<void>;
  /** Delete a correlation */
  delete(activityId: string): Promise<void>;
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Normalize legacy activity status to modern format
 */
export function normalizeActivityStatus(
  status: ActivityStatus | LegacyActivityStatus
): ActivityStatus {
  const legacyMap: Record<LegacyActivityStatus, ActivityStatus> = {
    'ACTIVITY_PENDING': 'pending',
    'ACTIVITY_IN_PROGRESS': 'running',
    'ACTIVITY_COMPLETED': 'completed',
    'ACTIVITY_FAILED': 'failed',
    'ACTIVITY_CANCELED': 'cancelled',
  };
  return legacyMap[status as LegacyActivityStatus] || (status as ActivityStatus);
}

